accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
            login, logout, password_reset, 
            password_reset_done,  password_reset_confirm,
            password_reset_complete
            )

app_name='accounts'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    # The dictionary needs to be "template_name" because Django knows it as that instead of the default template
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html','post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'post_reset_redirect': 'accounts:password_reset_complete', 'template_name': 'accounts/password_reset_confirm.html'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete, {'template_name': 'accounts/password_reset_complete.html'}, name='password_reset_complete'),

  
    
]

funorb/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from funorb import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
        
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return str(self.user) + ' - ' + str(self.description)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username', 
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from accounts.forms import (
        RegistrationForm,
        EditProfileForm)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponse
from django.views import View
from django.urls import reverse

# Create your views here.

def home(request):
    return render(request, 'accounts/home.html')

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:login'))

    else:

        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else :
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

funorb/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %} 
{% block head %}
<title>Change Password</title>
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %} 
{% block head %}
<title>Edit Profile</title>
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button> 
    </form>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1>Home</h1>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %} 
{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>
        Login
    </h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %} 
{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
    <p>
        You have logged out!
    </p>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %} {% block head %}
<title>Reset Completed</title>
{% endblock %} {% block body %}
<h1>Password reset complete</h1>
<p>Your password has been successfully reset. Please head to the <a href="{% url 'accounts:login' %}">login</a> page.</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %} 
{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
    <h1>Enter new password</h1>
    <p>
            Please enter your new password twice so we can verify you typed it in correctly.
    </p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change My Password</button>
    </form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %} 
{% block head %}
<title>{{ user }}'s Profile</title>
{% endblock %}

{% block body %}
    <h1>Profile</h1>
    <a href="{% url 'accounts:edit_profile' %}">Edit Profile</a> |              
    <a href="{% url 'accounts:change_password' %}">Change Password</a>

    <p>
         
        
        
        
    </p>
    <p>Username: {{ user }}</p>
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: <a href="{{ user.userprofile.website }}">{{ user.userprofile.website }}</a></p>
    <div><img src="{{ user.userprofile.image.url }}" width="240"></div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block head %} <title>Register</title> {% endblock %}
{% block body %} 

<h1>Register</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>


{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %} 
{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
    <h1>Password Reset</h1>
    <p>
            Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>

{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %} 
{% block head %}
<title>Reset Done</title>
{% endblock %} 

{% block body %}
<h1>Password reset sent</h1>
<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive
    them shortly.</p>
<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>

{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css"> {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Untitled</title>
    {% endblock %}
</head>

<body>
    <br>
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                        aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Untitled</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">

                    {% if user.is_authenticated %}

                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="{% url 'accounts:home' %}">Home</a>
                        </li>
                        
                        
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'accounts:view_profile' %}">Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:logout' %}">Log out</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'accounts:reset_password' %}">Reset Password</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'accounts:login' %}">Log in</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        
                        
                    </ul>
                    {% endif %}
                </div>
            </div>
            <!--/.nav-collapse -->

    </div>
    <!--/.container-fluid -->
    </nav>

    <div class="container">
        {% block body %} {% endblock %}
    </div>





    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>

</body>

</html>